module.exports = {
    DASHBOARD_MAX_LIFE: 3600,
    PRESENCE_UPDATE_INTERVAL: 600,
    VOICE_UPDATE_COOLDOWN: 30,
    LIBRARY_MAX_LENGTH: 10,
    SONG_MAX_DISPLAY: 60,
    QUEUE_MAX_LENGTH: 2000,
    QUEUE_MAX_DISPLAY: 25,
    BAR_MAX_DISPLAY: 20,
    MONGO_AUTO_INDEX: false,
    MONGO_MAX_POOL_SIZE: 10,
    MONGO_SERVER_SELECTION_TIMEOUT_MS: 5000,
    MONGO_SOCKET_TIMEOUT_MS: 45000,
    MONGO_FAMILY: 4,
    DISTUBE_LEAVE_ON_FINISH: false,
    DISTUBE_LEAVE_ON_STOP: false,
    DISTUBE_EMIT_ON_EMPTY: true,
    DISTUBE_EMPTY_COOLDOWN: 300,
    DISTUBE_NSFW: true,
    DISTUBE_SAVE_PREVIOUS_SONGS: false,
    DISTUBE_CUSTOM_FILTERS: { "8d": "apulsator=hz=0.08", "purebass": "bass=g=20,dynaudnorm=f=200,asubboost", "subboost": "asubboost", "fast": "atempo=1.3", "vibrato": "vibrato=f=6.5", "pulsator": "apulsator=hz=1" },
    DISTUBE_YOUTUBE_COOKIE: [{ "domain": ".youtube.com", "expirationDate": 1724928630.652595, "hostOnly": false, "httpOnly": true, "name": "__Secure-1PSIDCC", "path": "/", "sameSite": "unspecified", "secure": true, "session": false, "value": "APoG2W_twM8bIvLqoWLypyE5YaHrYhuf1GdQbugW5AkrEJ8zzLhnIZ4C4JRckoqSQUr9aca23zY" }],
    DISTUBE_YOUTUBE_IDENTITY_TOKEN: "QUFFLUhqa0NLTk01ZUdIaWYxQ3JydGFJVkEwbUsybENpd3w\u003d",
}