module.exports = {
    "en": {
        DASHBOARD_SONG_NO_PLAYING: "No song playing currently",
        DASHBOARD_QUEUE: "Queue:",
        DASHBOARD_QUEUE_NONE: "Join a voice channel and send a song name or a link.",
        DASHBOARD_QUEUE_NO_SONG: "No song in the queue.",
        DASHBOARD_VOLUME: "Volume:",
        DASHBOARD_REPEAT_SONG: "Repeat: Song",
        DASHBOARD_REPEAT_QUEUE: "Repeat: Queue",
        DASHBOARD_AUTOPLAY_ON: "Autoplay: On",
        DASHBOARD_FILTERS: "Filters:",
        DASHBOARD_SLASH_COMMANDS: "New slash commands available",
        COMMAND_AUTOPLAY_DESCRIPTION: "Enable or disable autoplay.",
        COMMAND_CLEAR_DESCRIPTION: "Clear the queue.",
        COMMAND_FILTER_DESCRIPTION: "Enable or disable a filter.",
        COMMAND_FIRST_DESCRIPTION: "Add a song or a playlist to the beginning of the queue.",
        COMMAND_INFO_DESCRIPTION: "Show information about the current song.",
        COMMAND_JUMP_DESCRIPTION: "Jump to a specific song in the queue.",
        COMMAND_LAST_DESCRIPTION: "Use your last query.",
        COMMAND_LIKE_DESCRIPTION: "Like the current song.",
        COMMAND_REMOVE_DESCRIPTION: "Remove a specific song from the queue.",
        COMMAND_REPLAY_DESCRIPTION: "Replay the current song.",
        COMMAND_RESET_DESCRIPTION: "Reset active filters.",
        COMMAND_SAVE_DESCRIPTION: "Use or save a query.",
        COMMAND_SAVE_OPTION: "The query to save.",
        COMMAND_SEARCH_DESCRIPTION: "Search and select a song to add to the queue.",
        COMMAND_SEEK_DESCRIPTION: "Seek a specific time in the current song.",
        COMMAND_SEEK_OPTION: "Time in the song (100 = 1m).",
        COMMAND_SETUP_DESCRIPTION: "Setup the dashboard.",
        COMMAND_SHUFFLE_DESCRIPTION: "Shuffle the queue.",
        MESSAGE_SONG_PLAYING: "Song playing",
        MESSAGE_SONG_REPLAYED: "Song replayed",
        MESSAGE_SONG_SKIPPED: "Song skipped",
        MESSAGE_SONG_SKIPPED_2: "Songs skipped to $position",
        MESSAGE_SONG_AUTHOR: "Author",
        MESSAGE_SONG_VIEWS: "Views",
        MESSAGE_SONG_LIKES: "Likes",
        MESSAGE_SONG_DURATION: "Duration",
        MESSAGE_SONG_LIKE: "$user likes this song!",
        MESSAGE_PLAYLIST_PLAYING: "Playlist playing",
        MESSAGE_QUEUE_SONG_ADDED: "Song added to queue",
        MESSAGE_QUEUE_SONG_REMOVED: "Song removed from the queue",
        MESSAGE_QUEUE_PLAYLIST_ADDED: "Playlist added to queue",
        MESSAGE_QUEUE_CLEARED: "Queue cleared",
        MESSAGE_QUEUE_SHUFFLED: "Queue shuffled",
        MESSAGE_AUTOPLAY_ENABLED: "Autoplay enabled",
        MESSAGE_AUTOPLAY_DISABLED: "Autoplay disabled",
        MESSAGE_FILTERS_ACTIVE: "Active filters:",
        MESSAGE_FILTERS_NONE: "None",
        MESSAGE_QUERY_SAVED: "Query saved",
        ERROR_SONG_NO_PLAYING: "No song playing currently",
        ERROR_SONG_NO_RELATED_FOUND: "No related song found",
        ERROR_SONG_NO_CORRECT_POSITION: "No song at this position",
        ERROR_SONG_TIME_GREATER: "Time greater than the song's duration",
        ERROR_PLAYLIST_UNKNOWN: "Unknown playlist",
        ERROR_QUEUE_NO_SONG: "No song in the queue",
        ERROR_FILTER_NO_ACTIVE: "No active filter",
        ERROR_QUERY_NO_SAVED: "No query saved",
        ERROR_QUERY_ALREADY_SAVED: "Query already saved",
        ERROR_QUERY_TOO_LONG: "Query too long",
        ERROR_VOICE_UNABLE_JOIN: "Unable to join the voice channel",
        ERROR_VOICE_DISCONNECTED: "Voice channel disconnected",
        ERROR_ACTION_TOO_FAST: "Action too fast",
        ERROR_ACTION_NOT_POSSIBLE: "Action not possible",
        ERROR_VIDEO_UNAVAILABLE: "Video unavailable",
        ERROR_VIDEO_RESTRICTED: "Video restricted",
        ERROR_URL_UNSUPPORTED: "URL unsupported",
        ERROR_RESULT_NO_FOUND: "No result found",
        ERROR_DASHBOARD_UNABLE_SETUP: "Unable to setup the dashboard in this channel",
        ERROR_COMMANDS_NOT_USABLE: "Commands not usable in this channel",
        ERROR_USER_NO_VOICE: "You must be in a voice channel",
        ERROR_USER_NO_VOICE_2: "You must be in my voice channel",
        ERROR_USER_NO_MANAGER: "You must have permission to manage server",
        ERROR_OCCURED: "An error has occurred",
        UPDATE_TITLE: "",
        UPDATE_DESCRIPTION: "",
    },
    "fr": {
        DASHBOARD_SONG_NO_PLAYING: "Aucune musique en cours de lecture",
        DASHBOARD_QUEUE: "File d'attente :",
        DASHBOARD_QUEUE_NONE: "Rejoignez un salon vocal et envoyez le nom d'une musique ou un lien.",
        DASHBOARD_QUEUE_NO_SONG: "Aucune musique dans la file d'attente.",
        DASHBOARD_VOLUME: "Volume :",
        DASHBOARD_REPEAT_SONG: "Répéter : Musique",
        DASHBOARD_REPEAT_QUEUE: "Répéter : File d'attente",
        DASHBOARD_AUTOPLAY_ON: "Lecture auto : Activé",
        DASHBOARD_FILTERS: "Filtres :",
        DASHBOARD_SLASH_COMMANDS: "Nouvelles commandes slash disponibles",
        COMMAND_AUTOPLAY_DESCRIPTION: "Activer ou désactiver la lecture automatique.",
        COMMAND_CLEAR_DESCRIPTION: "Vider la file d'attente.",
        COMMAND_FILTER_DESCRIPTION: "Activer ou désactiver un filtre.",
        COMMAND_FIRST_DESCRIPTION: "Ajouter une musique ou une playlist au début de la file d'attente.",
        COMMAND_INFO_DESCRIPTION: "Afficher des informations sur la musique en cours de lecture.",
        COMMAND_JUMP_DESCRIPTION: "Passer à une musique spécifique dans la file d'attente.",
        COMMAND_LAST_DESCRIPTION: "Utiliser votre dernière requête.",
        COMMAND_LIKE_DESCRIPTION: "Aimer la musique en cours de lecture.",
        COMMAND_REMOVE_DESCRIPTION: "Retirer une musique spécifique de la file d'attente.",
        COMMAND_REPLAY_DESCRIPTION: "Rejouer la musique en cours de lecture.",
        COMMAND_RESET_DESCRIPTION: "Réinitialiser les filtres actifs.",
        COMMAND_SAVE_DESCRIPTION: "Utiliser ou sauvegarder une requête.",
        COMMAND_SAVE_OPTION: "La requête à sauvegarder.",
        COMMAND_SEARCH_DESCRIPTION: "Chercher et sélectionner une musique à ajouter à la file d'attente.",
        COMMAND_SEEK_DESCRIPTION: "Aller à un moment spécifique dans la musique en cours de lecture.",
        COMMAND_SEEK_OPTION: "Moment dans la musique (100 = 1m).",
        COMMAND_SETUP_DESCRIPTION: "Installer le tableau de bord.",
        COMMAND_SHUFFLE_DESCRIPTION: "Mélanger la file d'attente.",
        MESSAGE_SONG_PLAYING: "Musique en cours de lecture",
        MESSAGE_SONG_REPLAYED: "Musique rejouée",
        MESSAGE_SONG_SKIPPED: "Musique passée",
        MESSAGE_SONG_SKIPPED_2: "Musiques passées jusqu'à $position",
        MESSAGE_SONG_AUTHOR: "Auteur",
        MESSAGE_SONG_VIEWS: "Vues",
        MESSAGE_SONG_LIKES: "Likes",
        MESSAGE_SONG_DURATION: "Durée",
        MESSAGE_SONG_LIKE: "$user aime cette musique !",
        MESSAGE_PLAYLIST_PLAYING: "Playlist en cours de lecture",
        MESSAGE_QUEUE_SONG_ADDED: "Musique ajoutée à la file d'attente",
        MESSAGE_QUEUE_SONG_REMOVED: "Musique supprimée de la file d'attente",
        MESSAGE_QUEUE_PLAYLIST_ADDED: "Playlist ajoutée à la file d'attente",
        MESSAGE_QUEUE_CLEARED: "File d'attente vidée",
        MESSAGE_QUEUE_SHUFFLED: "File d'attente mélangée",
        MESSAGE_AUTOPLAY_ENABLED: "Lecture automatique activée",
        MESSAGE_AUTOPLAY_DISABLED: "Lecture automatique désactivée",
        MESSAGE_FILTERS_ACTIVE: "Filtres actifs :",
        MESSAGE_FILTERS_NONE: "Aucun",
        MESSAGE_QUERY_SAVED: "Requête sauvegardée",
        ERROR_SONG_NO_PLAYING: "Aucune musique en cours de lecture",
        ERROR_SONG_NO_RELATED_FOUND: "Aucune musique similaire trouvée",
        ERROR_SONG_NO_CORRECT_POSITION: "Aucune musique à cette position",
        ERROR_SONG_TIME_GREATER: "Moment supérieur à la durée de la musique",
        ERROR_PLAYLIST_UNKNOWN: "Playlist inconnue",
        ERROR_QUEUE_NO_SONG: "Aucune musique dans la file d'attente",
        ERROR_FILTER_NO_ACTIVE: "Aucun filtre actif",
        ERROR_QUERY_NO_SAVED: "Aucune requête sauvegardée",
        ERROR_QUERY_ALREADY_SAVED: "Requête déjà sauvegardée",
        ERROR_QUERY_TOO_LONG: "Requête trop longue",
        ERROR_VOICE_UNABLE_JOIN: "Impossible de rejoindre le salon vocal",
        ERROR_VOICE_DISCONNECTED: "Salon vocal déconnecté",
        ERROR_ACTION_TOO_FAST: "Action trop rapide",
        ERROR_ACTION_NOT_POSSIBLE: "Action impossible",
        ERROR_VIDEO_UNAVAILABLE: "Vidéo indisponible",
        ERROR_VIDEO_RESTRICTED: "Vidéo restreinte",
        ERROR_URL_UNSUPPORTED: "URL non prise en charge",
        ERROR_RESULT_NO_FOUND: "Aucun résultat trouvé",
        ERROR_DASHBOARD_UNABLE_SETUP: "Impossible d'installer le tableau de bord dans ce salon",
        ERROR_COMMANDS_NOT_USABLE: "Commandes non utilisables dans ce salon",
        ERROR_USER_NO_VOICE: "Vous devez être dans un salon vocal",
        ERROR_USER_NO_VOICE_2: "Vous devez être dans mon salon vocal",
        ERROR_USER_NO_MANAGER: "Vous devez avoir la permission de gérer le serveur",
        ERROR_OCCURED: "Une erreur est survenue",
        UPDATE_TITLE: "",
        UPDATE_DESCRIPTION: "",
    },
}