module.exports = {
    "en": {
        DASHBOARD_SONG_NO_PLAYING: "No song playing currently",
        DASHBOARD_QUEUE: "Queue:",
        DASHBOARD_QUEUE_NONE: "Join a voice channel and send a song name or a link.",
        DASHBOARD_QUEUE_NO_SONG: "No song in the queue.",
        DASHBOARD_VOLUME: "Volume:",
        DASHBOARD_REPEAT_SONG: "Repeat: Song",
        DASHBOARD_REPEAT_QUEUE: "Repeat: Queue",
        DASHBOARD_AUTOPLAY_ON: "Autoplay: On",
        DASHBOARD_FILTERS: "Filters:",
        COMMAND_AUTOPLAY_DESCRIPTION: "Enable or disable autoplay.",
        COMMAND_CLEAR_DESCRIPTION: "Clear the queue.",
        COMMAND_FILTER_DESCRIPTION: "Manage filters.",
        COMMAND_FILTER_TOGGLE_DESCRIPTION: "Enable or disable a filter.",
        COMMAND_FILTER_TOGGLE_OPTION: "The filter name.",
        COMMAND_FILTER_RESET_DESCRIPTION: "Reset active filters.",
        COMMAND_FIRST_DESCRIPTION: "Add a song or a playlist to the beginning of the queue.",
        COMMAND_FIRST_OPTION: "The song name or a link.",
        COMMAND_INFO_DESCRIPTION: "Show information about the current song.",
        COMMAND_JUMP_DESCRIPTION: "Jump to a specific song in the queue.",
        COMMAND_JUMP_OPTION: "The song's position in the queue.",
        COMMAND_LAST_DESCRIPTION: "Use your last query.",
        COMMAND_LIBRARY_DESCRIPTION: "Manage your library.",
        COMMAND_LIBRARY_PLAY_DESCRIPTION: "Show your library and select an item to add to the queue.",
        COMMAND_LIBRARY_ADD_DESCRIPTION: "Add the currently playing song or playlist to your library.",
        COMMAND_LIBRARY_REMOVE_DESCRIPTION: "Remove an item from your library.",
        COMMAND_LIBRARY_REMOVE_OPTION: "The item's position in your library.",
        COMMAND_REMOVE_DESCRIPTION: "Remove a specific song from the queue.",
        COMMAND_REMOVE_OPTION: "The song's position in the queue.",
        COMMAND_REPLAY_DESCRIPTION: "Replay the current song.",
        COMMAND_SEARCH_DESCRIPTION: "Search and select a song to add to the queue.",
        COMMAND_SEARCH_OPTION: "The song name.",
        COMMAND_SEEK_DESCRIPTION: "Seek a specific time in the current song.",
        COMMAND_SEEK_OPTION: "The time in the song (100 = 1m).",
        COMMAND_SETUP_DESCRIPTION: "Setup the dashboard in this channel.",
        COMMAND_SETUP_OPTION: "The Flopy's language.",
        COMMAND_SHUFFLE_DESCRIPTION: "Shuffle the queue.",
        MESSAGE_SONG_PLAYING: "Song playing",
        MESSAGE_SONG_REPLAYED: "Song replayed",
        MESSAGE_SONG_SKIPPED: "Song(s) skipped to $position",
        MESSAGE_SONG_AUTHOR: "Author",
        MESSAGE_SONG_VIEWS: "Views",
        MESSAGE_SONG_LIKES: "Likes",
        MESSAGE_SONG_DURATION: "Duration",
        MESSAGE_PLAYLIST_PLAYING: "Playlist playing",
        MESSAGE_QUEUE_SONG_ADDED: "Song added to queue",
        MESSAGE_QUEUE_SONG_REMOVED: "Song removed from the queue",
        MESSAGE_QUEUE_PLAYLIST_ADDED: "Playlist added to queue",
        MESSAGE_QUEUE_CLEARED: "Queue cleared",
        MESSAGE_QUEUE_SHUFFLED: "Queue shuffled",
        MESSAGE_AUTOPLAY_ENABLED: "Autoplay enabled",
        MESSAGE_AUTOPLAY_DISABLED: "Autoplay disabled",
        MESSAGE_FILTERS_ACTIVE: "Active filters:",
        MESSAGE_FILTERS_NONE: "None",
        MESSAGE_LIBRARY_TITLE: "Library",
        MESSAGE_LIBRARY_NAME: "Name",
        MESSAGE_LIBRARY_SONGS: "Songs",
        MESSAGE_LIBRARY_PLAYLISTS: "Playlists",
        MESSAGE_LIBRARY_SONG_ADDED: "Song added to your library",
        MESSAGE_LIBRARY_SONG_REMOVED: "Song removed from your library",
        MESSAGE_LIBRARY_PLAYLIST_ADDED: "Playlist added to your library",
        MESSAGE_LIBRARY_PLAYLIST_REMOVED: "Playlist removed from your library",
        ERROR_SONG_NO_PLAYING: "No song playing currently",
        ERROR_SONG_NO_RELATED_FOUND: "No related song found",
        ERROR_SONG_INVALID_POSITION: "No song at this position",
        ERROR_SONG_TIME_GREATER: "Time greater than the song's duration",
        ERROR_PLAYLIST_UNKNOWN: "Unknown playlist",
        ERROR_QUEUE_NO_SONG: "No song in the queue",
        ERROR_FILTER_NO_ACTIVE: "No active filter",
        ERROR_LIBRARY_NO_ITEM: "No item added to your library",
        ERROR_LIBRARY_LIMIT_REACHED: "Limit of your library reached",
        ERROR_LIBRARY_SONG_ALREADY_ADDED: "Song already added to your library",
        ERROR_LIBRARY_PLAYLIST_ALREADY_ADDED: "Playlist already added to your library",
        ERROR_ITEM_INVALID_POSITION: "No item at this position",
        ERROR_VOICE_UNABLE_JOIN: "Unable to join the voice channel",
        ERROR_VOICE_DISCONNECTED: "Voice channel disconnected",
        ERROR_VIDEO_UNAVAILABLE: "Video unavailable",
        ERROR_VIDEO_RESTRICTED: "Video restricted",
        ERROR_URL_UNSUPPORTED: "URL unsupported",
        ERROR_RESULT_NO_FOUND: "No result found",
        ERROR_DASHBOARD_UNABLE_SETUP: "Unable to setup the dashboard in this channel",
        ERROR_COMMAND_NOT_USABLE: "Command not usable in this channel",
        ERROR_ACTION_NOT_POSSIBLE: "Action not possible at the moment",
        ERROR_USER_MUST_JOIN_VOICE: "You must join a voice channel",
        ERROR_USER_MUST_JOIN_VOICE_2: "You must join my voice channel",
        ERROR_USER_MUST_BE_MANAGER: "You must have permission to manage server",
        ERROR_OCCURED: "An error has occurred",
        HELP_MESSAGE: "Help message",
        HELP_PLAY_SONG: "Join a voice channel and send a song name or a link in $channel.",
        HELP_SETUP_DASHBOARD: "Use $command command in a channel to setup the dashboard.",
    },
    "fr": {
        DASHBOARD_SONG_NO_PLAYING: "Aucune musique en cours de lecture",
        DASHBOARD_QUEUE: "File d'attente :",
        DASHBOARD_QUEUE_NONE: "Rejoignez un salon vocal et envoyez le nom d'une musique ou un lien.",
        DASHBOARD_QUEUE_NO_SONG: "Aucune musique dans la file d'attente.",
        DASHBOARD_VOLUME: "Volume :",
        DASHBOARD_REPEAT_SONG: "Répéter : Musique",
        DASHBOARD_REPEAT_QUEUE: "Répéter : File d'attente",
        DASHBOARD_AUTOPLAY_ON: "Lecture auto : Activé",
        DASHBOARD_FILTERS: "Filtres :",
        COMMAND_AUTOPLAY_DESCRIPTION: "Activer ou désactiver la lecture automatique.",
        COMMAND_CLEAR_DESCRIPTION: "Vider la file d'attente.",
        COMMAND_FILTER_DESCRIPTION: "Gérer les filtres.",
        COMMAND_FILTER_TOGGLE_DESCRIPTION: "Activer ou désactiver un filtre.",
        COMMAND_FILTER_TOGGLE_OPTION: "Le nom du filtre.",
        COMMAND_FILTER_RESET_DESCRIPTION: "Réinitialiser les filtres actifs.",
        COMMAND_FIRST_DESCRIPTION: "Ajouter une musique ou une playlist au début de la file d'attente.",
        COMMAND_FIRST_OPTION: "Le nom de la musique ou un lien.",
        COMMAND_INFO_DESCRIPTION: "Afficher des informations sur la musique en cours de lecture.",
        COMMAND_JUMP_DESCRIPTION: "Passer à une musique spécifique dans la file d'attente.",
        COMMAND_JUMP_OPTION: "La position de la musique dans la file d'attente.",
        COMMAND_LAST_DESCRIPTION: "Utiliser votre dernière requête.",
        COMMAND_LIBRARY_DESCRIPTION: "Gérer votre bibliothèque.",
        COMMAND_LIBRARY_PLAY_DESCRIPTION: "Afficher votre bibliothèque et sélectionner un élément à ajouter à la file d'attente.",
        COMMAND_LIBRARY_ADD_DESCRIPTION: "Ajouter la musique ou la playlist en cours de lecture à votre bibliothèque.",
        COMMAND_LIBRARY_REMOVE_DESCRIPTION: "Supprimer un élément de votre bibliothèque.",
        COMMAND_LIBRARY_REMOVE_OPTION: "La position de l'élément dans votre bibliothèque.",
        COMMAND_REMOVE_DESCRIPTION: "Retirer une musique spécifique de la file d'attente.",
        COMMAND_REMOVE_OPTION: "La position de la musique dans la file d'attente.",
        COMMAND_REPLAY_DESCRIPTION: "Rejouer la musique en cours de lecture.",
        COMMAND_SEARCH_DESCRIPTION: "Chercher et sélectionner une musique à ajouter à la file d'attente.",
        COMMAND_SEARCH_OPTION: "Le nom de la musique.",
        COMMAND_SEEK_DESCRIPTION: "Aller à un moment spécifique dans la musique en cours de lecture.",
        COMMAND_SEEK_OPTION: "Le moment dans la musique (100 = 1m).",
        COMMAND_SETUP_DESCRIPTION: "Installer le tableau de bord dans ce salon.",
        COMMAND_SETUP_OPTION: "La langue de Flopy.",
        COMMAND_SHUFFLE_DESCRIPTION: "Mélanger la file d'attente.",
        MESSAGE_SONG_PLAYING: "Musique en cours de lecture",
        MESSAGE_SONG_REPLAYED: "Musique rejouée",
        MESSAGE_SONG_SKIPPED: "Musique(s) passée(s) jusqu'à $position",
        MESSAGE_SONG_AUTHOR: "Auteur",
        MESSAGE_SONG_VIEWS: "Vues",
        MESSAGE_SONG_LIKES: "Likes",
        MESSAGE_SONG_DURATION: "Durée",
        MESSAGE_PLAYLIST_PLAYING: "Playlist en cours de lecture",
        MESSAGE_QUEUE_SONG_ADDED: "Musique ajoutée à la file d'attente",
        MESSAGE_QUEUE_SONG_REMOVED: "Musique supprimée de la file d'attente",
        MESSAGE_QUEUE_PLAYLIST_ADDED: "Playlist ajoutée à la file d'attente",
        MESSAGE_QUEUE_CLEARED: "File d'attente vidée",
        MESSAGE_QUEUE_SHUFFLED: "File d'attente mélangée",
        MESSAGE_AUTOPLAY_ENABLED: "Lecture automatique activée",
        MESSAGE_AUTOPLAY_DISABLED: "Lecture automatique désactivée",
        MESSAGE_FILTERS_ACTIVE: "Filtres actifs :",
        MESSAGE_FILTERS_NONE: "Aucun",
        MESSAGE_LIBRARY_TITLE: "Bibliothèque",
        MESSAGE_LIBRARY_NAME: "Nom",
        MESSAGE_LIBRARY_SONGS: "Musiques",
        MESSAGE_LIBRARY_PLAYLISTS: "Playlists",
        MESSAGE_LIBRARY_SONG_ADDED: "Musique ajoutée à votre bibliothèque",
        MESSAGE_LIBRARY_SONG_REMOVED: "Musique supprimée de votre bibliothèque",
        MESSAGE_LIBRARY_PLAYLIST_ADDED: "Playlist ajoutée à votre bibliothèque",
        MESSAGE_LIBRARY_PLAYLIST_REMOVED: "Playlist supprimée de votre bibliothèque",
        ERROR_SONG_NO_PLAYING: "Aucune musique en cours de lecture",
        ERROR_SONG_NO_RELATED_FOUND: "Aucune musique similaire trouvée",
        ERROR_SONG_INVALID_POSITION: "Aucune musique à cette position",
        ERROR_SONG_TIME_GREATER: "Moment supérieur à la durée de la musique",
        ERROR_PLAYLIST_UNKNOWN: "Playlist inconnue",
        ERROR_QUEUE_NO_SONG: "Aucune musique dans la file d'attente",
        ERROR_FILTER_NO_ACTIVE: "Aucun filtre actif",
        ERROR_LIBRARY_NO_ITEM: "Aucun élément ajouté à votre bibliothèque",
        ERROR_LIBRARY_LIMIT_REACHED: "Limite de votre bibliothèque atteinte",
        ERROR_LIBRARY_SONG_ALREADY_ADDED: "Musique déjà ajoutée à votre bibliothèque",
        ERROR_LIBRARY_PLAYLIST_ALREADY_ADDED: "Playlist déjà ajoutée à votre bibliothèque",
        ERROR_ITEM_INVALID_POSITION: "Aucun élément à cette position",
        ERROR_VOICE_UNABLE_JOIN: "Impossible de rejoindre le salon vocal",
        ERROR_VOICE_DISCONNECTED: "Salon vocal déconnecté",
        ERROR_VIDEO_UNAVAILABLE: "Vidéo indisponible",
        ERROR_VIDEO_RESTRICTED: "Vidéo restreinte",
        ERROR_URL_UNSUPPORTED: "URL non prise en charge",
        ERROR_RESULT_NO_FOUND: "Aucun résultat trouvé",
        ERROR_DASHBOARD_UNABLE_SETUP: "Impossible d'installer le tableau de bord dans ce salon",
        ERROR_COMMAND_NOT_USABLE: "Commande non utilisable dans ce salon",
        ERROR_ACTION_NOT_POSSIBLE: "Action impossible pour le moment",
        ERROR_USER_MUST_JOIN_VOICE: "Vous devez rejoindre un salon vocal",
        ERROR_USER_MUST_JOIN_VOICE_2: "Vous devez rejoindre mon salon vocal",
        ERROR_USER_MUST_BE_MANAGER: "Vous devez avoir la permission de gérer le serveur",
        ERROR_OCCURED: "Une erreur est survenue",
        HELP_MESSAGE: "Message d'aide",
        HELP_PLAY_SONG: "Rejoignez un salon vocal et envoyez le nom d'une musique ou un lien dans $channel.",
        HELP_SETUP_DASHBOARD: "Utilisez la commande $command dans un salon pour intaller le tableau de bord.",
    },
}