module.exports = {
    TOKEN: "OTA5NTM0MTUxMTEwMTg5MTU2.YZFrrw.uI7QkhGOxH_0jKnQyUtOGyx-Jvc",
    DBCONNECTION: "mongodb+srv://Extrymes:'gCGkCy76*J*s`n@flopy.ockfu.mongodb.net/Flopy?retryWrites=true&w=majority",
    GUILD_DEFAULTSETTINGS: {
        dashboard1: { channel: "", message: "", language: "en" },
        dashboard2: { channel: "", message: "", language: "en" },
        dashboard3: { channel: "", message: "", language: "en" },
    },
    USER_DEFAULTSETTINGS: {
        playlist: [],
    },
    PREFIX: ".",
    INVITE_FLOPY: "https://discord.com/api/oauth2/authorize?client_id=909205146863566858&permissions=3172352&scope=bot",
    INVITE_FLOPY2: "https://discord.com/api/oauth2/authorize?client_id=909533411247546368&permissions=3172352&scope=bot",
    INVITE_FLOPY3: "https://discord.com/api/oauth2/authorize?client_id=909533975809232926&permissions=3172352&scope=bot",
    QUEUE_MAX_DISPLAY: 20,
    DISTUBE_EVENTS: [ "playSong", "addSong", "addList", "deleteQueue", "searchNoResult", "noRelated", "disconnect", "empty", "error" ],
    DISTUBE_LEAVE_ON_FINISH: false,
    DISTUBE_LEAVE_ON_STOP: false,
    DISTUBE_PAUSE_ON_EMPTY: true,
    DISTUBE_EMIT_NEW_SONG_ONLY: false,
    DISTUBE_SEARCH_SONG: 0,
    DISTUBE_SEARCH_COOLDOWN: 60,
    DISTUBE_EMPTY_COOLDOWN: 60,
    DISTUBE_NSFW: true,
    DISTUBE_CUSTOM_FILTERS: { "8d": "apulsator=hz=0.08", "purebass": "bass=g=20,dynaudnorm=f=200,asubboost", "subboost": "asubboost", "fast": "atempo=1.3", "vibrato": "vibrato=f=6.5", "pulsator": "apulsator=hz=1" },
    DISTUBE_YOUTUBE_DL: false,
    DISTUBE_UPDATE_YOUTUBE_DL: false,
    DISTUBE_YOUTUBE_COOKIE: "SID=Egh5UqA2VSZPQIIcpeeHTns_WExW8EE96MEYF7S52oLu3a2cdPKin5Kd9r3RJKq1iW89Bw.; __Secure-1PSID=Egh5UqA2VSZPQIIcpeeHTns_WExW8EE96MEYF7S52oLu3a2clCtRIfTqwTeY9coZmlVFsA.; __Secure-3PSID=Egh5UqA2VSZPQIIcpeeHTns_WExW8EE96MEYF7S52oLu3a2cIF3-b-3SxBXrY2vr87wd3g.; HSID=A9bkf03oXpycqSiEJ; SSID=AdMbwd8GYqaES4bjW; APISID=1a3XXKkl35NU1xEW/AT-xaPcn_b39QwtCY; SAPISID=VAHjYVxihjXnfhdu/A54S0RztXAkiGNfMj; __Secure-1PAPISID=VAHjYVxihjXnfhdu/A54S0RztXAkiGNfMj; __Secure-3PAPISID=VAHjYVxihjXnfhdu/A54S0RztXAkiGNfMj; YSC=VwZxCoah6rA; VISITOR_INFO1_LIVE=JNETNm_O2rQ; LOGIN_INFO=AFmmF2swRAIgWRjk2MO3g5I-kj_mqWCec5FdbaJ5e4M9jZTQZ520ZkECIAyBQ9zOfP9Z-fLVr8RgBDfcazH1z2SqB3RkTBKNvdjf:QUQ3MjNmeF9STEw5ZU5yRDVpNzJZRF8tbmpHSjRMZ1lwNjJnay1CYm9MWjVja25KWGt6aWU1MlJ2ckQ2WFdsLVlkRi03OG9DaHNpSnhTMlAwaElyQzRpMHZKZmU3ZWIzVkNscUIwMG5yTXYyTGswWFp0T1VJQVRCTFNsVFFnbUFqcDdFTXg2V0J6OXRKU0YwbjlvTDJPdWNtcFFSY0tYbjNn; PREF=tz=Europe.Brussels; SIDCC=AJi4QfFr_7KEdGk7J5pmqnx0HQKyR0Tc1JTNbjje9af86yOwkSwG0OJm7PV8HDIHHkGI_xdd; __Secure-3PSIDCC=AJi4QfEizL-xmKoMEeIfBrMSHPZBe7mLMDzdVfHcMO2FRjPiDm1PcwcW-W3RK-buiA3D-oAP",
}
