module.exports = {
  "en": {
    DASHBOARD_SONG_NO_PLAYING: "No song playing currently",
    DASHBOARD_QUEUE: "Queue:",
    DASHBOARD_QUEUE_NONE: "Join a voice channel and send a song name or a link.",
    DASHBOARD_QUEUE_NO_SONG: "No song in the queue.",
    DASHBOARD_VOLUME: "Volume:",
    DASHBOARD_REPEAT_SONG: "Repeat: Song",
    DASHBOARD_REPEAT_QUEUE: "Repeat: Queue",
    DASHBOARD_AUTOPLAY_ON: "Autoplay: On",
    DASHBOARD_FILTERS: "Filters:",
    COMMAND_AUTOPLAY_DESCRIPTION: "Toggle autoplay.",
    COMMAND_FILTER_DESCRIPTION: "Manage filters.",
    COMMAND_FILTER_TOGGLE_DESCRIPTION: "Toggle a filter.",
    COMMAND_FILTER_TOGGLE_OPTION_NAME: "The filter name.",
    COMMAND_FILTER_RESET_DESCRIPTION: "Reset active filters.",
    COMMAND_FIRST_DESCRIPTION: "Add an item to the beginning of the queue.",
    COMMAND_FIRST_OPTION_QUERY: "The song name or a link.",
    COMMAND_INFO_DESCRIPTION: "Show information about the current song.",
    COMMAND_JOIN_DESCRIPTION: "Join your voice channel.",
    COMMAND_JUMP_DESCRIPTION: "Jump to a specific song in the queue.",
    COMMAND_JUMP_OPTION_POSITION: "The song's position in the queue.",
    COMMAND_LAST_DESCRIPTION: "Use your last query.",
    COMMAND_LIBRARY_DESCRIPTION: "Manage your library.",
    COMMAND_LIBRARY_VIEW_DESCRIPTION: "Display your library and interact with items.",
    COMMAND_LIBRARY_ADD_DESCRIPTION: "Add the currently playing item to your library.",
    COMMAND_LIBRARY_REMOVE_DESCRIPTION: "Remove a specific item from your library.",
    COMMAND_LIBRARY_REMOVE_OPTION_POSITION: "The item's position in your library.",
    COMMAND_REMOVE_DESCRIPTION: "Manage the queue.",
    COMMAND_REMOVE_SONG_DESCRIPTION: "Remove a specific song from the queue.",
    COMMAND_REMOVE_SONG_OPTION_POSITION: "The song's position in the queue.",
    COMMAND_REMOVE_ALL_DESCRIPTION: "Clear the queue.",
    COMMAND_REPLAY_DESCRIPTION: "Replay the current song.",
    COMMAND_SEARCH_DESCRIPTION: "Search and interact with results.",
    COMMAND_SEARCH_OPTION_QUERY: "The song, the artist, the lyrics, and more.",
    COMMAND_SEARCH_OPTION_TYPE: "The search result type.",
    COMMAND_SEEK_DESCRIPTION: "Seek a specific time in the current song.",
    COMMAND_SEEK_OPTION_TIME: "The time in the song (hours, minutes, seconds).",
    COMMAND_SETUP_DESCRIPTION: "Setup the dashboard in this channel.",
    COMMAND_SETUP_OPTION_LANGUAGE: "The Flopy's language.",
    COMMAND_SHUFFLE_DESCRIPTION: "Shuffle the queue.",
    COMMAND_VOLUME_DESCRIPTION: "Set the volume percentage.",
    COMMAND_VOLUME_OPTION_PERCENTAGE: "The volume percentage (1-100%).",
    MESSAGE_SONG_PLAYING: "Song playing",
    MESSAGE_SONG_REPLAYED: "Song replayed",
    MESSAGE_SONG_SKIPPED: "Song(s) skipped to $position",
    MESSAGE_PLAYLIST_PLAYING: "Playlist playing",
    MESSAGE_QUEUE_SONG_ADDED: "Song added to the queue",
    MESSAGE_QUEUE_SONG_REMOVED: "Song removed from the queue",
    MESSAGE_QUEUE_PLAYLIST_ADDED: "Playlist added to the queue",
    MESSAGE_QUEUE_CLEARED: "Queue cleared",
    MESSAGE_QUEUE_SHUFFLED: "Queue shuffled",
    MESSAGE_ITEM_TITLE: "Title",
    MESSAGE_ITEM_AUTHOR: "Author",
    MESSAGE_ITEM_VIEWS: "Views",
    MESSAGE_ITEM_LIKES: "Likes",
    MESSAGE_ITEM_DURATION: "Duration",
    MESSAGE_AUTOPLAY_ENABLED: "Autoplay enabled",
    MESSAGE_AUTOPLAY_DISABLED: "Autoplay disabled",
    MESSAGE_FILTERS_ACTIVE: "Active filters:",
    MESSAGE_FILTERS_NONE: "None",
    MESSAGE_LIBRARY_TITLE: "Your library",
    MESSAGE_LIBRARY_SONG_ADDED: "Song added to your library",
    MESSAGE_LIBRARY_PLAYLIST_ADDED: "Playlist added to your library",
    MESSAGE_SEARCH_TITLE: "Search results",
    MESSAGE_VOLUME_SET: "Volume set to $percentage",
    MESSAGE_VOICE_CHANNEL_JOINED: "Voice channel joined",
    MESSAGE_DASHBOARD_INSTALLED: "Dashboard installed in this channel",
    ERROR_SONG_NO_PLAYING: "No song playing currently",
    ERROR_SONG_NO_RELATED_FOUND: "No related song found",
    ERROR_SONG_INVALID_POSITION: "No song at this position",
    ERROR_SONG_TIME_GREATER: "Time greater than the song's duration",
    ERROR_PLAYLIST_UNKNOWN: "Unknown playlist",
    ERROR_QUEUE_NO_SONG: "No song in the queue",
    ERROR_FILTER_NO_ACTIVE: "No active filter",
    ERROR_LIBRARY_NO_ITEM: "No item added to your library",
    ERROR_LIBRARY_LIMIT_REACHED: "Limit of your library reached",
    ERROR_LIBRARY_SONG_NOT_FOUND: "Song not found in your library",
    ERROR_LIBRARY_SONG_ALREADY_ADDED: "Song already added to your library",
    ERROR_LIBRARY_PLAYLIST_NOT_FOUND: "Playlist not found in your library",
    ERROR_LIBRARY_PLAYLIST_ALREADY_ADDED: "Playlist already added to your library",
    ERROR_VOLUME_ALREADY_SET: "Volume already set to $percentage",
    ERROR_VOLUME_INVALID_PERCENTAGE: "Invalid volume percentage",
    ERROR_VOICE_CHANNEL_UNABLE_JOIN: "Unable to join the voice channel",
    ERROR_VOICE_CHANNEL_DISCONNECTED: "Voice channel disconnected",
    ERROR_VOICE_CHANNEL_ALREADY_JOINED: "Voice channel already joined",
    ERROR_VIDEO_UNAVAILABLE: "Unavailable video",
    ERROR_VIDEO_RESTRICTED: "Restricted video",
    ERROR_URL_UNSUPPORTED: "Unsupported URL",
    ERROR_URL_INVALID: "Invalid URL",
    ERROR_RESULT_NO_FOUND: "No result found",
    ERROR_DASHBOARD_UNABLE_SETUP: "Unable to setup the dashboard in this channel",
    ERROR_COMMAND_NOT_USABLE: "Command not usable in this channel",
    ERROR_ACTION_NOT_POSSIBLE: "Action not possible at the moment",
    ERROR_MEMBER_MUST_JOIN_VOICE_CHANNEL: "You must join a voice channel",
    ERROR_MEMBER_MUST_JOIN_MY_VOICE_CHANNEL: "You must join my voice channel",
    ERROR_MEMBER_MUST_BE_MANAGER: "You must have permission to manage server",
    ERROR_UNKNOWN: "An unknown error has occurred",
    HELP_MESSAGE: "Help message",
    HELP_PLAY_SONG: "Join a voice channel and send a song name or a link in $channel.",
    HELP_SETUP_DASHBOARD: "Use $command command in a channel to setup the dashboard.",
    BUTTON_PLAY: "Play",
    BUTTON_LIBRARY_ADD: "Add to your library",
    BUTTON_LIBRARY_REMOVE: "Remove from your library"
  },
  "fr": {
    DASHBOARD_SONG_NO_PLAYING: "Aucune musique en cours de lecture",
    DASHBOARD_QUEUE: "File d'attente :",
    DASHBOARD_QUEUE_NONE: "Rejoignez un salon vocal et envoyez le nom d'une musique ou un lien.",
    DASHBOARD_QUEUE_NO_SONG: "Aucune musique dans la file d'attente.",
    DASHBOARD_VOLUME: "Volume :",
    DASHBOARD_REPEAT_SONG: "Répéter : Musique",
    DASHBOARD_REPEAT_QUEUE: "Répéter : File d'attente",
    DASHBOARD_AUTOPLAY_ON: "Lecture auto : Activé",
    DASHBOARD_FILTERS: "Filtres :",
    COMMAND_AUTOPLAY_DESCRIPTION: "Basculer la lecture automatique.",
    COMMAND_FILTER_DESCRIPTION: "Gérer les filtres.",
    COMMAND_FILTER_TOGGLE_DESCRIPTION: "Basculer un filtre.",
    COMMAND_FILTER_TOGGLE_OPTION_NAME: "Le nom du filtre.",
    COMMAND_FILTER_RESET_DESCRIPTION: "Réinitialiser les filtres actifs.",
    COMMAND_FIRST_DESCRIPTION: "Ajouter un élément au début de la file d'attente.",
    COMMAND_FIRST_OPTION_QUERY: "Le nom de la musique ou un lien.",
    COMMAND_INFO_DESCRIPTION: "Afficher des informations sur la musique en cours de lecture.",
    COMMAND_JOIN_DESCRIPTION: "Rejoindre votre salon vocal.",
    COMMAND_JUMP_DESCRIPTION: "Passer à une musique spécifique dans la file d'attente.",
    COMMAND_JUMP_OPTION_POSITION: "La position de la musique dans la file d'attente.",
    COMMAND_LAST_DESCRIPTION: "Utiliser votre dernière requête.",
    COMMAND_LIBRARY_DESCRIPTION: "Gérer votre bibliothèque.",
    COMMAND_LIBRARY_VIEW_DESCRIPTION: "Afficher votre bibliothèque et intéragir avec les éléments.",
    COMMAND_LIBRARY_ADD_DESCRIPTION: "Ajouter l'élément en cours de lecture à votre bibliothèque.",
    COMMAND_LIBRARY_REMOVE_DESCRIPTION: "Retirer un élément spécifique de votre bibliothèque.",
    COMMAND_LIBRARY_REMOVE_OPTION_POSITION: "La position de l'élément dans votre bibliothèque.",
    COMMAND_REMOVE_DESCRIPTION: "Gérer la file d'attente.",
    COMMAND_REMOVE_SONG_DESCRIPTION: "Retirer une musique spécifique de la file d'attente.",
    COMMAND_REMOVE_SONG_OPTION_POSITION: "La position de la musique dans la file d'attente.",
    COMMAND_REMOVE_ALL_DESCRIPTION: "Vider la file d'attente.",
    COMMAND_REPLAY_DESCRIPTION: "Rejouer la musique en cours de lecture.",
    COMMAND_SEARCH_DESCRIPTION: "Rechercher et intéragir avec les résultats.",
    COMMAND_SEARCH_OPTION_QUERY: "La musique, l'artiste, les paroles, etc.",
    COMMAND_SEARCH_OPTION_TYPE: "Le type de résultat de recherche.",
    COMMAND_SEEK_DESCRIPTION: "Aller à un moment spécifique dans la musique en cours de lecture.",
    COMMAND_SEEK_OPTION_TIME: "Le moment dans la musique (heures, minutes, secondes).",
    COMMAND_SETUP_DESCRIPTION: "Installer le tableau de bord dans ce salon.",
    COMMAND_SETUP_OPTION_LANGUAGE: "La langue de Flopy.",
    COMMAND_SHUFFLE_DESCRIPTION: "Mélanger la file d'attente.",
    COMMAND_VOLUME_DESCRIPTION: "Régler le pourcentage du volume.",
    COMMAND_VOLUME_OPTION_PERCENTAGE: "Le pourcentage du volume (1-100%).",
    MESSAGE_SONG_PLAYING: "Musique en cours de lecture",
    MESSAGE_SONG_REPLAYED: "Musique rejouée",
    MESSAGE_SONG_SKIPPED: "Musique(s) passée(s) jusqu'à $position",
    MESSAGE_PLAYLIST_PLAYING: "Playlist en cours de lecture",
    MESSAGE_QUEUE_SONG_ADDED: "Musique ajoutée à la file d'attente",
    MESSAGE_QUEUE_SONG_REMOVED: "Musique supprimée de la file d'attente",
    MESSAGE_QUEUE_PLAYLIST_ADDED: "Playlist ajoutée à la file d'attente",
    MESSAGE_QUEUE_CLEARED: "File d'attente vidée",
    MESSAGE_QUEUE_SHUFFLED: "File d'attente mélangée",
    MESSAGE_ITEM_TITLE: "Titre",
    MESSAGE_ITEM_AUTHOR: "Auteur",
    MESSAGE_ITEM_VIEWS: "Vues",
    MESSAGE_ITEM_LIKES: "Likes",
    MESSAGE_ITEM_DURATION: "Durée",
    MESSAGE_AUTOPLAY_ENABLED: "Lecture automatique activée",
    MESSAGE_AUTOPLAY_DISABLED: "Lecture automatique désactivée",
    MESSAGE_FILTERS_ACTIVE: "Filtres actifs :",
    MESSAGE_FILTERS_NONE: "Aucun",
    MESSAGE_LIBRARY_TITLE: "Votre bibliothèque",
    MESSAGE_LIBRARY_SONG_ADDED: "Musique ajoutée à votre bibliothèque",
    MESSAGE_LIBRARY_PLAYLIST_ADDED: "Playlist ajoutée à votre bibliothèque",
    MESSAGE_SEARCH_TITLE: "Résultats de recherche",
    MESSAGE_VOLUME_SET: "Volume réglé à $percentage",
    MESSAGE_VOICE_CHANNEL_JOINED: "Salon vocal rejoint",
    MESSAGE_DASHBOARD_INSTALLED: "Tableau de bord installé dans ce salon",
    ERROR_SONG_NO_PLAYING: "Aucune musique en cours de lecture",
    ERROR_SONG_NO_RELATED_FOUND: "Aucune musique similaire trouvée",
    ERROR_SONG_INVALID_POSITION: "Aucune musique à cette position",
    ERROR_SONG_TIME_GREATER: "Moment supérieur à la durée de la musique",
    ERROR_PLAYLIST_UNKNOWN: "Playlist inconnue",
    ERROR_QUEUE_NO_SONG: "Aucune musique dans la file d'attente",
    ERROR_FILTER_NO_ACTIVE: "Aucun filtre actif",
    ERROR_LIBRARY_NO_ITEM: "Aucun élément ajouté à votre bibliothèque",
    ERROR_LIBRARY_LIMIT_REACHED: "Limite de votre bibliothèque atteinte",
    ERROR_LIBRARY_SONG_NOT_FOUND: "Musique introuvable dans votre bibliothèque",
    ERROR_LIBRARY_SONG_ALREADY_ADDED: "Musique déjà ajoutée à votre bibliothèque",
    ERROR_LIBRARY_PLAYLIST_NOT_FOUND: "Playlist introuvable dans votre bibliothèque",
    ERROR_LIBRARY_PLAYLIST_ALREADY_ADDED: "Playlist déjà ajoutée à votre bibliothèque",
    ERROR_VOLUME_ALREADY_SET: "Volume déjà réglé à $percentage",
    ERROR_VOLUME_INVALID_PERCENTAGE: "Pourcentage de volume invalide",
    ERROR_VOICE_CHANNEL_UNABLE_JOIN: "Impossible de rejoindre le salon vocal",
    ERROR_VOICE_CHANNEL_DISCONNECTED: "Salon vocal déconnecté",
    ERROR_VOICE_CHANNEL_ALREADY_JOINED: "Salon vocal déjà rejoint",
    ERROR_VIDEO_UNAVAILABLE: "Vidéo indisponible",
    ERROR_VIDEO_RESTRICTED: "Vidéo restreinte",
    ERROR_URL_UNSUPPORTED: "URL non prise en charge",
    ERROR_URL_INVALID: "URL invalide",
    ERROR_RESULT_NO_FOUND: "Aucun résultat trouvé",
    ERROR_DASHBOARD_UNABLE_SETUP: "Impossible d'installer le tableau de bord dans ce salon",
    ERROR_COMMAND_NOT_USABLE: "Commande non utilisable dans ce salon",
    ERROR_ACTION_NOT_POSSIBLE: "Action impossible pour le moment",
    ERROR_MEMBER_MUST_JOIN_VOICE_CHANNEL: "Vous devez rejoindre un salon vocal",
    ERROR_MEMBER_MUST_JOIN_MY_VOICE_CHANNEL: "Vous devez rejoindre mon salon vocal",
    ERROR_MEMBER_MUST_BE_MANAGER: "Vous devez avoir la permission de gérer le serveur",
    ERROR_UNKNOWN: "Une erreur inconnue s'est produite",
    HELP_MESSAGE: "Message d'aide",
    HELP_PLAY_SONG: "Rejoignez un salon vocal et envoyez le nom d'une musique ou un lien dans $channel.",
    HELP_SETUP_DASHBOARD: "Utilisez la commande $command dans un salon pour installer le tableau de bord.",
    BUTTON_PLAY: "Jouer",
    BUTTON_LIBRARY_ADD: "Ajouter à votre bibliothèque",
    BUTTON_LIBRARY_REMOVE: "Supprimer de votre bibliothèque"
  }
}